#!/usr/bin/env python3
import glob, os

command = "gcc -W -Wall -std=c++23 -o main -Iinclude -Llib -lncurses -ltinfo -lm -pipe -O3 -lstdc++"
command+= " " 
command += " ".join(glob.glob("./**/*.cpp", recursive=True))

print(f"Executing: {command}")

os.system(command)
